#!/bin/sh
wmname LG3D
xrdb ~/.Xresources
sxhkd -c /home/timur/.config/sxhkd/sxhkdrc &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap		 5
bspc config top_padding	 	 0
bspc config left_padding	-0
bspc config right_padding	-0
bspc config bottom_padding	-5

bspc config border_width 2

# bspc config focused_border_color "#1de81c"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       false

bspc rule -a Chromium desktop='^2'
bspc rule -a Zathura state=tiled
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# keyboard layout changing
setxkbmap -layout us,ru -option grp:shifts_toggle

# wallpaper manager
# nitrogen --restore &

# polybar
polybar -r main

